# version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db-go-social
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5438:5432"

volumes:
  db_data: